### ISSUE TITLE
Some minor issue I encountered when playing with the doc

### ISSUE THREAD

**Issue by altkennyh2l** [Haixiang6123/overwatch-ui#1]
Hello! I am new to Vue and am having a lot of fun exploring this project.
But I found some minor tiny issue when I am playing with the doc. 

## Sidebar is gone on mobile view
Viewing on an iPhone, sidebar is gone and only show up in landscape mode.

## Loading icon do not spin in centre (on mobile devices)
On both iPhone and iPad, and with Safari, the loading icon on button do not spin in a centre. 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/16442958/54517654-42bebb80-499d-11e9-8484-c87894db8840.gif)

(FPS reduced as converted to gif, but the wobbling can still be seen.)

## Icon on button are close together
I don't know if this is a design choice or something else, but the text and icon in buttons are too close together in my opinion (especially for the UP and DOWN button shown in doc). I saw some hit for a 4px margin in the source (I probably misread), but Chrome show no spacing between text and icon in a button, the same also apply to the Safari view as shown above.

(Same opinion for the radio and checkbox components, text may be too close to the selector)

## Font in popover messages
Again, I don't know if this is on purpose but the font on popover message is completely different than every font in the doc. (font not specified?)

---
Again, I am new to Vue and these word may not be something useful but just a bit of my experience with the project. Thank you for creating this and I enjoyed learning from it a lot. :D

**Comment by Haixiang6123** [comment]
@altkennyh2l Thanks for pointing out the problems, but right now I am preparing my finals in this quarter. So it may take a week for me to look deep in the Issues. I'll fix them ASAP.

**Comment by Guyanqi** [comment]
I have same issue
